### ISSUE TITLE
Does not working on MacOS

### ISSUE THREAD

**Issue by sergey-drpa** [nixxcode/jvm-brotli#34]
Mojave 10.14.6

`java.lang.RuntimeException: java.io.FileNotFoundException: File /lib/darwin-x86-amd64/libbrotli.dylib was not found inside JAR.
	at com.nixxcode.jvmbrotli.common.BrotliLoader.loadBrotli(BrotliLoader.java:85)
	at com.nixxcode.jvmbrotli.common.BrotliLoader.isBrotliAvailable(BrotliLoader.java:63)
	at Test$Companion.main(Test.kt:15)
	at Test.main(Test.kt)`

**Comment by parambirs** [comment]
+1. I'm facing the same problem on Mac

```
Caused by: java.io.FileNotFoundException: File /lib/darwin-x86-amd64/libbrotli.dylib was not found inside JAR.
	at com.nixxcode.jvmbrotli.common.NativeUtils.loadLibraryFromJar(NativeUtils.java:123)
	at com.nixxcode.jvmbrotli.common.BrotliLoader.loadBrotli(BrotliLoader.java:82)
	... 10 more
```

I've included the dependency in my build.gradle as follows:

```
compile 'com.nixxcode.jvmbrotli:jvmbrotli:0.2.0'
```

**Comment by Akshay586** [comment]
Had this issue where the dependency resolution worked for windows. but on making a maven jar it failed to recognize the same over on ubuntu server.
Had to manually insert the dependency's jar into the package, it worked like a charm afterward.
